2021-06-25 21:43:32.173999: 
Traceback (most recent call last):
  File "C:\Users\willg\eclipse-workspace\TestingTabler\BadWolfBot.py", line 1799, in on_message
    await help.send_help(message, is_lounge_server, args, server_prefix)
  File "C:\Users\willg\eclipse-workspace\TestingTabler\help.py", line 58, in send_help
    for line in f:
  File "C:\Users\willg\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1411: character maps to <undefined>

2022-01-11 00:51:38.037910: 
Traceback (most recent call last):
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 715, in add_data
    await RoomTracker.add_everything_to_database(deepcopied_channel_bot)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 689, in add_everything_to_database
    event_structure_data_dump_event_id = await sql_helper.dump_event_structure_data()
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 672, in dump_event_structure_data
    return await db_connection.execute(upsert_script, event_structure_tuple)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 92, in execute
    cursor = await self.con.execute(*args)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table Event_Structure has no column named manual_dc_placements

2022-01-11 00:51:42.412869: 
Traceback (most recent call last):
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 715, in add_data
    await RoomTracker.add_everything_to_database(deepcopied_channel_bot)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 689, in add_everything_to_database
    event_structure_data_dump_event_id = await sql_helper.dump_event_structure_data()
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 672, in dump_event_structure_data
    return await db_connection.execute(upsert_script, event_structure_tuple)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 92, in execute
    cursor = await self.con.execute(*args)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table Event_Structure has no column named manual_dc_placements

2022-01-11 00:51:54.923515: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 00:51:55.016645: 
Traceback (most recent call last):
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 715, in add_data
    await RoomTracker.add_everything_to_database(deepcopied_channel_bot)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 689, in add_everything_to_database
    event_structure_data_dump_event_id = await sql_helper.dump_event_structure_data()
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 672, in dump_event_structure_data
    return await db_connection.execute(upsert_script, event_structure_tuple)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 92, in execute
    cursor = await self.con.execute(*args)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table Event_Structure has no column named manual_dc_placements

2022-01-11 00:51:59.845162: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 00:52:01.083312: 
Traceback (most recent call last):
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 715, in add_data
    await RoomTracker.add_everything_to_database(deepcopied_channel_bot)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 689, in add_everything_to_database
    event_structure_data_dump_event_id = await sql_helper.dump_event_structure_data()
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 672, in dump_event_structure_data
    return await db_connection.execute(upsert_script, event_structure_tuple)
  File "c:\Users\ryanz\OneDrive\Desktop\GitHub\MKW-Table-Bot\data_tracking\DataTracker.py", line 92, in execute
    cursor = await self.con.execute(*args)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table Event_Structure has no column named manual_dc_placements

2022-01-11 01:01:50.528942: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 01:01:55.003133: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 01:04:25.913214: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 01:04:31.547585: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 01:05:42.289179: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 01:05:46.385137: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 01:06:44.471663: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb
2022-01-11 01:06:50.050238: The following track had no SHA mapping: 9f09ddb05bc5c7b04bb7aa120f6d0f21774143eb